### ISSUE TITLE
Node 6 support

### ISSUE THREAD

**Issue by mattclement** [ibm-messaging/mqlight-fishalive-node#3]
When is node 6 support coming?

**Comment by dnwe** [comment]
@cleme1mp We are in the process of getting the MQ Light Node client working with Node 6. We decided to take this as an opportunity to move away from the underlying native code and have a pure Node.js implementation. As such the next refresh of the client will represent a significant rewrite and is taking us a little longer to complete. The hope is having a pure Node.js implementation will allow the client to work out of the box with future Node levels without requiring a MQ Light client refresh.

There is an unsupported test version which we've tried on Windows and Linux (but should work on MacOS also) available under mqlight-dev on npmjs.com. Note that is is a major version level refresh. We will be pushing updates to mqlight-dev as we continue to bug fix prior to promoting the final client.

I can't give a firm date to the fully supported version going live, but it should be in the realm of weeks rather than months - if that helps!
